<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="SmokleTestscenario" duration-ms="55" started-at="2017-12-29T22:05:51Z" finished-at="2017-12-29T22:05:51Z">
    <groups>
    </groups>
    <test name="Sprint1" duration-ms="55" started-at="2017-12-29T22:05:51Z" finished-at="2017-12-29T22:05:51Z">
      <class name="testNGclass.Testcase1">
        <test-method status="PASS" signature="TestFB()[pri:0, instance:testNGclass.Testcase1@16f7c8c1]" name="TestFB" duration-ms="12" started-at="2017-12-29T17:05:51Z" finished-at="2017-12-29T17:05:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestFB -->
      </class> <!-- testNGclass.Testcase1 -->
      <class name="testNGclass.Testcase2">
        <test-method status="PASS" signature="TestTwiter()[pri:0, instance:testNGclass.Testcase2@fcd6521]" name="TestTwiter" duration-ms="2" started-at="2017-12-29T17:05:51Z" finished-at="2017-12-29T17:05:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestTwiter -->
      </class> <!-- testNGclass.Testcase2 -->
      <class name="testNGclass.Testcase3">
        <test-method status="FAIL" signature="TestWatsup()[pri:0, instance:testNGclass.Testcase3@27d415d9]" name="TestWatsup" duration-ms="4" started-at="2017-12-29T17:05:51Z" finished-at="2017-12-29T17:05:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at testNGclass.Testcase3.TestWatsup(Testcase3.java:10)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestWatsup -->
      </class> <!-- testNGclass.Testcase3 -->
    </test> <!-- Sprint1 -->
  </suite> <!-- SmokleTestscenario -->
</testng-results>
